version: "3.9"

services:
  web:
    build: .
    container_name: dxconnect_web
    command: ["/app/docker/entrypoint.sh"]
    env_file:
      - .env
      - env.example
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

  db:
    image: postgres:15-alpine
    container_name: dxconnect_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: dxconnect_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:

