# Generated by Django 4.2.13 on 2025-09-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='config',
            constraint=models.UniqueConstraint(models.Value(1), name='config_singleton', violation_error_message='Apenas uma configuração é permitida.'),
        ),
    ]
