# Generated by Django 4.2.13 on 2025-09-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_config_config_singleton'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='appearance_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
