# Generated by Django 4.2.13 on 2025-09-27 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_config_whatsapp_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'permissions': (('manage_config_company', 'Pode gerenciar Config - Company'), ('manage_config_chat', 'Pode gerenciar Config - Chat'), ('manage_config_email', 'Pode gerenciar Config - Email'), ('manage_config_appearance', 'Pode gerenciar Config - Appearance'), ('manage_config_whatsapp', 'Pode gerenciar Config - WhatsApp')), 'verbose_name': 'Configuração', 'verbose_name_plural': 'Configurações'},
        ),
    ]
