# Generated by Django 4.2.13 on 2025-10-07 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_config_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'permissions': (('manage_config_company', 'Pode gerenciar Config - Company'), ('manage_config_chat', 'Pode gerenciar Config - Chat'), ('manage_config_email', 'Pode gerenciar Config - Email'), ('manage_config_appearance', 'Pode gerenciar Config - Appearance'), ('manage_config_whatsapp', 'Pode gerenciar Config - WhatsApp'), ('manage_config_documents', 'Pode gerenciar Config - Document Templates')), 'verbose_name': 'Configuração', 'verbose_name_plural': 'Configurações'},
        ),
        migrations.AddField(
            model_name='config',
            name='document_templates',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
