# Generated by Django 4.2.13 on 2025-09-27 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'permissions': (('manage_auth', 'Pode gerenciar autenticação (grupos e permissões)'),), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
