# Generated by Django 4.2.13 on 2025-10-11 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_agent_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciasNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('som_nova_mensagem', models.BooleanField(default=True, help_text='Tocar som ao receber nova mensagem', verbose_name='Som - Nova Mensagem')),
                ('som_novo_atendimento', models.BooleanField(default=True, help_text='Tocar som ao receber novo atendimento', verbose_name='Som - Novo Atendimento')),
                ('som_transferencia', models.BooleanField(default=True, help_text='Tocar som ao receber atendimento transferido', verbose_name='Som - Transferência')),
                ('desktop_nova_mensagem', models.BooleanField(default=True, help_text='Mostrar notificação desktop para nova mensagem', verbose_name='Desktop - Nova Mensagem')),
                ('desktop_novo_atendimento', models.BooleanField(default=True, verbose_name='Desktop - Novo Atendimento')),
                ('desktop_transferencia', models.BooleanField(default=True, verbose_name='Desktop - Transferência')),
                ('mostrar_badge_mensagens', models.BooleanField(default=True, help_text='Mostrar contador de mensagens não lidas', verbose_name='Badge de Mensagens')),
                ('mostrar_badge_atendimentos', models.BooleanField(default=True, help_text='Mostrar contador de atendimentos pendentes', verbose_name='Badge de Atendimentos')),
                ('modo_nao_perturbe', models.BooleanField(default=False, help_text='Desabilita todas as notificações sonoras', verbose_name='Modo Não Perturbe')),
                ('nao_perturbe_inicio', models.TimeField(blank=True, help_text='Horário de início (ex: 22:00)', null=True, verbose_name='Não Perturbe - Início')),
                ('nao_perturbe_fim', models.TimeField(blank=True, help_text='Horário de fim (ex: 08:00)', null=True, verbose_name='Não Perturbe - Fim')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_notificacao', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Preferências de Notificação',
                'verbose_name_plural': 'Preferências de Notificação',
            },
        ),
    ]
