# Generated by Django 4.2.13 on 2025-10-12 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_preferencias_notificacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('busy', 'Ocupado'), ('away', 'Ausente')], db_index=True, default='offline', max_length=10, verbose_name='Status')),
                ('status_message', models.CharField(blank=True, help_text="Ex: 'Em reunião até 15h'", max_length=255, verbose_name='Mensagem de Status')),
                ('last_heartbeat', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Último Heartbeat')),
                ('websocket_connected', models.BooleanField(default=False, verbose_name='WebSocket Conectado')),
                ('status_changed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Status Alterado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presence', to=settings.AUTH_USER_MODEL, verbose_name='Agente')),
            ],
            options={
                'verbose_name': 'Presença de Agente',
                'verbose_name_plural': 'Presenças de Agentes',
            },
        ),
        migrations.CreateModel(
            name='TypingIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(db_index=True, max_length=100, verbose_name='ID do Chat')),
                ('is_typing', models.BooleanField(default=False, verbose_name='Está Digitando')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Começou a Digitar em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_indicators', to=settings.AUTH_USER_MODEL, verbose_name='Agente')),
            ],
            options={
                'verbose_name': 'Indicador de Digitação',
                'verbose_name_plural': 'Indicadores de Digitação',
                'indexes': [models.Index(fields=['chat_id', 'is_typing'], name='accounts_ty_chat_id_1f2a7d_idx')],
                'unique_together': {('agent', 'chat_id')},
            },
        ),
    ]
