# Generated by Django 4.2.13 on 2025-10-11 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('disconnected', 'Desconectado'), ('connecting', 'Conectando'), ('qrcode', 'Aguardando QR Code'), ('authenticated', 'Autenticado'), ('ready', 'Pronto'), ('error', 'Erro')], db_index=True, default='disconnected', max_length=20, verbose_name='Status')),
                ('device_name', models.CharField(blank=True, help_text='Nome do dispositivo conectado', max_length=255, verbose_name='Nome do Dispositivo')),
                ('phone_number', models.CharField(blank=True, help_text='Número do WhatsApp conectado', max_length=20, verbose_name='Número de Telefone')),
                ('qr_code', models.TextField(blank=True, help_text='QR Code em base64 para autenticação', verbose_name='QR Code')),
                ('session_data', models.TextField(blank=True, help_text='Dados criptografados da sessão para reconexão', verbose_name='Dados de Sessão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Atualizado em')),
                ('connected_at', models.DateTimeField(blank=True, help_text='Data e hora da última conexão bem-sucedida', null=True, verbose_name='Conectado em')),
                ('disconnected_at', models.DateTimeField(blank=True, help_text='Data e hora da última desconexão', null=True, verbose_name='Desconectado em')),
                ('total_messages_sent', models.IntegerField(default=0, verbose_name='Total de Mensagens Enviadas')),
                ('total_messages_received', models.IntegerField(default=0, verbose_name='Total de Mensagens Recebidas')),
                ('last_message_at', models.DateTimeField(blank=True, help_text='Data e hora da última mensagem enviada ou recebida', null=True, verbose_name='Última Mensagem em')),
                ('last_error', models.TextField(blank=True, help_text='Descrição do último erro ocorrido', verbose_name='Último Erro')),
                ('error_count', models.IntegerField(default=0, help_text='Número de erros desde a última conexão', verbose_name='Contagem de Erros')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('usuario', models.ForeignKey(help_text='Usuário responsável pela sessão', on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Sessão WhatsApp',
                'verbose_name_plural': 'Sessões WhatsApp',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, help_text='ID único da mensagem no WhatsApp', max_length=255, unique=True, verbose_name='ID da Mensagem')),
                ('client_message_id', models.CharField(blank=True, help_text='ID gerado pelo cliente para rastreamento', max_length=255, verbose_name='ID do Cliente')),
                ('direction', models.CharField(choices=[('inbound', 'Recebida'), ('outbound', 'Enviada')], db_index=True, max_length=10, verbose_name='Direção')),
                ('message_type', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagem'), ('audio', 'Áudio'), ('video', 'Vídeo'), ('document', 'Documento'), ('location', 'Localização'), ('contact', 'Contato'), ('sticker', 'Sticker')], default='text', max_length=20, verbose_name='Tipo de Mensagem')),
                ('chat_id', models.CharField(db_index=True, help_text='ID do chat/conversa no WhatsApp', max_length=100, verbose_name='ID do Chat')),
                ('contact_number', models.CharField(help_text='Número de telefone do remetente/destinatário', max_length=20, verbose_name='Número do Contato')),
                ('contact_name', models.CharField(blank=True, help_text='Nome salvo do contato', max_length=255, verbose_name='Nome do Contato')),
                ('text_content', models.TextField(blank=True, verbose_name='Conteúdo de Texto')),
                ('media_url', models.URLField(blank=True, max_length=500, verbose_name='URL da Mídia')),
                ('media_mime_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo MIME da Mídia')),
                ('media_size', models.IntegerField(blank=True, null=True, verbose_name='Tamanho da Mídia (bytes)')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Dados completos da mensagem em formato JSON', verbose_name='Payload Completo')),
                ('status', models.CharField(choices=[('queued', 'Na Fila'), ('sent', 'Enviada'), ('delivered', 'Entregue'), ('read', 'Lida'), ('failed', 'Falhou'), ('error', 'Erro')], db_index=True, default='queued', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('queued_at', models.DateTimeField(auto_now_add=True, verbose_name='Na Fila em')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Entregue em')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lido em')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('is_from_me', models.BooleanField(default=False, help_text='Indica se a mensagem foi enviada pelo usuário autenticado', verbose_name='De Mim')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp.whatsappsession', verbose_name='Sessão')),
                ('usuario', models.ForeignKey(help_text='Usuário responsável pela mensagem', on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Mensagem WhatsApp',
                'verbose_name_plural': 'Mensagens WhatsApp',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='whatsappsession',
            index=models.Index(fields=['usuario', 'status'], name='whatsapp_wh_usuario_063419_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappsession',
            index=models.Index(fields=['status', 'is_active'], name='whatsapp_wh_status_415286_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['session', 'created_at'], name='whatsapp_wh_session_1aa106_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['chat_id', 'created_at'], name='whatsapp_wh_chat_id_322b52_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['direction', 'status'], name='whatsapp_wh_directi_db7ab1_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['usuario', 'created_at'], name='whatsapp_wh_usuario_f6a747_idx'),
        ),
    ]
