# Generated by Django 4.2.13 on 2025-10-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='protocol_version',
            field=models.CharField(default='v1', help_text='Versão do protocolo de comunicação (v1, v2, etc)', max_length=10, verbose_name='Versão do Protocolo'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='raw_payload',
            field=models.JSONField(blank=True, default=dict, help_text='Payload bruto recebido do webhook/API, sem processamento', verbose_name='Payload Bruto'),
        ),
    ]
