# Generated by Django 4.2.13 on 2025-10-11 22:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_add_raw_payload_protocol_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappsession',
            name='auto_reconnect',
            field=models.BooleanField(default=True, help_text='Tentar reconectar automaticamente em caso de desconexão', verbose_name='Reconexão Automática'),
        ),
        migrations.AddField(
            model_name='whatsappsession',
            name='last_reconnect_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Tentativa de Reconexão'),
        ),
        migrations.AddField(
            model_name='whatsappsession',
            name='proxy_enabled',
            field=models.BooleanField(default=False, verbose_name='Proxy Habilitado'),
        ),
        migrations.AddField(
            model_name='whatsappsession',
            name='proxy_url',
            field=models.CharField(blank=True, help_text='Ex: http://proxy.example.com:8080', max_length=500, verbose_name='URL do Proxy'),
        ),
        migrations.AddField(
            model_name='whatsappsession',
            name='reconnect_attempts',
            field=models.IntegerField(default=0, help_text='Número de tentativas de reconexão desde a última falha', verbose_name='Tentativas de Reconexão'),
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ID do Arquivo')),
                ('original_url', models.URLField(help_text='URL da mídia no WhatsApp', max_length=1000, verbose_name='URL Original')),
                ('media_type', models.CharField(choices=[('image', 'Imagem'), ('audio', 'Áudio'), ('video', 'Vídeo'), ('document', 'Documento'), ('sticker', 'Sticker')], max_length=20, verbose_name='Tipo de Mídia')),
                ('mime_type', models.CharField(max_length=100, verbose_name='Tipo MIME')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='Tamanho (bytes)')),
                ('duration_seconds', models.IntegerField(blank=True, null=True, verbose_name='Duração (segundos)')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Largura (px)')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Altura (px)')),
                ('original_file', models.FileField(blank=True, null=True, upload_to='whatsapp/media/original/%Y/%m/%d/', verbose_name='Arquivo Original')),
                ('converted_file', models.FileField(blank=True, help_text='Versão otimizada para web', null=True, upload_to='whatsapp/media/converted/%Y/%m/%d/', verbose_name='Arquivo Convertido')),
                ('thumbnail_file', models.ImageField(blank=True, null=True, upload_to='whatsapp/media/thumbnails/%Y/%m/%d/', verbose_name='Thumbnail')),
                ('file_hash', models.CharField(blank=True, db_index=True, help_text='Para evitar duplicatas', max_length=64, verbose_name='Hash SHA-256')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('downloading', 'Baixando'), ('processing', 'Processando'), ('ready', 'Pronto'), ('error', 'Erro')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('downloaded_at', models.DateTimeField(blank=True, null=True, verbose_name='Baixado em')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processado em')),
                ('download_time_ms', models.IntegerField(blank=True, null=True, verbose_name='Tempo de Download (ms)')),
                ('processing_time_ms', models.IntegerField(blank=True, null=True, verbose_name='Tempo de Processamento (ms)')),
                ('is_public', models.BooleanField(default=False, help_text='Se True, não requer autenticação', verbose_name='Público')),
                ('access_count', models.IntegerField(default=0, verbose_name='Contador de Acessos')),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True, verbose_name='Último Acesso')),
                ('message', models.ForeignKey(help_text='Mensagem WhatsApp associada', on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='whatsapp.whatsappmessage', verbose_name='Mensagem')),
            ],
            options={
                'verbose_name': 'Arquivo de Mídia',
                'verbose_name_plural': 'Arquivos de Mídia',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='whatsapp_me_status_1cf54a_idx'), models.Index(fields=['file_hash'], name='whatsapp_me_file_ha_f91cc4_idx'), models.Index(fields=['message', 'media_type'], name='whatsapp_me_message_4fb736_idx')],
            },
        ),
    ]
