# Generated by Django 4.2.13 on 2025-10-06 21:04

from django.db import migrations, models
import django.core.validators
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20251006_1755'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Criar modelo GrupoEmpresa
        migrations.CreateModel(
            name='GrupoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Grupo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Grupo de Empresas',
                'verbose_name_plural': 'Grupos de Empresas',
                'ordering': ['nome'],
            },
        ),
        
        # Adicionar campo grupo_empresa ao Cliente
        migrations.AddField(
            model_name='cliente',
            name='grupo_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas', to='clientes.grupoempresa', verbose_name='Grupo de Empresas'),
        ),
        
        # Atualizar modelo ContatoCliente
        migrations.AlterModelOptions(
            name='contatocliente',
            options={'ordering': ['nome'], 'verbose_name': 'Contato da Empresa', 'verbose_name_plural': 'Contatos das Empresas'},
        ),
        
        # Remover campos desnecessários do ContatoCliente
        migrations.RemoveField(
            model_name='contatocliente',
            name='tipo_contato',
        ),
        migrations.RemoveField(
            model_name='contatocliente',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='contatocliente',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='contatocliente',
            name='observacoes',
        ),
        
        # Tornar WhatsApp obrigatório
        migrations.AlterField(
            model_name='contatocliente',
            name='whatsapp',
            field=models.CharField(help_text='WhatsApp da pessoa (obrigatório para chat)', max_length=20, validators=[django.core.validators.RegexValidator(message='Formato de WhatsApp inválido. Use: +5511999999999', regex='^\\+?1?\\d{9,15}$')], verbose_name='WhatsApp'),
        ),
        
        # Adicionar unique_together para cliente + whatsapp
        migrations.AlterUniqueTogether(
            name='contatocliente',
            unique_together={('cliente', 'whatsapp')},
        ),
        
        # Adicionar índices
        migrations.AddIndex(
            model_name='grupoempresa',
            index=models.Index(fields=['nome'], name='clientes_grupoempresa_nome_idx'),
        ),
        migrations.AddIndex(
            model_name='grupoempresa',
            index=models.Index(fields=['ativo'], name='clientes_grupoempresa_ativo_idx'),
        ),
        migrations.AddIndex(
            model_name='contatocliente',
            index=models.Index(fields=['whatsapp'], name='clientes_contatocliente_whatsapp_idx'),
        ),
    ]
