# Generated by Django 4.2.13 on 2025-10-07 01:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0003_auto_20251006_1804'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cliente',
            name='clientes_cl_documen_76f212_idx',
        ),
        migrations.RemoveIndex(
            model_name='cliente',
            name='clientes_cl_nome_b2cdde_idx',
        ),
        migrations.RemoveIndex(
            model_name='cliente',
            name='clientes_cliente_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='cliente',
            name='clientes_cliente_criado_em_idx',
        ),
        migrations.RemoveIndex(
            model_name='contatocliente',
            name='clientes_contatocliente_tipo_contato_idx',
        ),
        migrations.RemoveIndex(
            model_name='grupoempresa',
            name='clientes_grupoempresa_nome_idx',
        ),
        migrations.RemoveIndex(
            model_name='grupoempresa',
            name='clientes_grupoempresa_ativo_idx',
        ),
        migrations.RenameIndex(
            model_name='cliente',
            new_name='clientes_cl_cnpj_db43af_idx',
            old_name='clientes_cliente_cnpj_idx',
        ),
        migrations.RenameIndex(
            model_name='cliente',
            new_name='clientes_cl_razao_s_83ac4e_idx',
            old_name='clientes_cliente_razao_social_idx',
        ),
        migrations.RenameIndex(
            model_name='cliente',
            new_name='clientes_cl_nome_fa_d1b939_idx',
            old_name='clientes_cliente_nome_fantasia_idx',
        ),
        migrations.RenameIndex(
            model_name='contatocliente',
            new_name='clientes_co_cliente_dd7912_idx',
            old_name='clientes_contatocliente_cliente_ativo_idx',
        ),
        migrations.RenameIndex(
            model_name='contatocliente',
            new_name='clientes_co_whatsap_6c111e_idx',
            old_name='clientes_contatocliente_whatsapp_idx',
        ),
        migrations.RenameIndex(
            model_name='contatocliente',
            new_name='clientes_co_nome_40a837_idx',
            old_name='clientes_contatocliente_nome_idx',
        ),
        migrations.RenameIndex(
            model_name='documentocliente',
            new_name='clientes_do_cliente_5c54c9_idx',
            old_name='clientes_documentocliente_cliente_tipo_idx',
        ),
        migrations.RenameIndex(
            model_name='documentocliente',
            new_name='clientes_do_data_up_065a04_idx',
            old_name='clientes_documentocliente_data_upload_idx',
        ),
        migrations.RenameIndex(
            model_name='historicocliente',
            new_name='clientes_hi_cliente_696752_idx',
            old_name='clientes_historicocliente_cliente_data_idx',
        ),
        migrations.RenameIndex(
            model_name='historicocliente',
            new_name='clientes_hi_campo_a_0edffc_idx',
            old_name='clientes_historicocliente_campo_alterado_idx',
        ),
        migrations.AddField(
            model_name='documentocliente',
            name='dados_preenchidos',
            field=models.JSONField(blank=True, default=dict, help_text='Dados usados para preencher o template', verbose_name='Dados Preenchidos'),
        ),
        migrations.AddField(
            model_name='documentocliente',
            name='data_vencimento',
            field=models.DateField(blank=True, help_text='Data de vencimento do documento (se aplicável)', null=True, verbose_name='Data de Vencimento'),
        ),
        migrations.AddField(
            model_name='documentocliente',
            name='origem',
            field=models.CharField(choices=[('manual', 'Upload Manual'), ('gerado', 'Gerado Automaticamente'), ('importado', 'Importado de Sistema')], default='manual', help_text='Como o documento foi criado', max_length=20, verbose_name='Origem'),
        ),
        migrations.AddField(
            model_name='documentocliente',
            name='status',
            field=models.CharField(choices=[('gerado', 'Gerado'), ('enviado', 'Enviado'), ('assinado', 'Assinado'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('expirado', 'Expirado')], default='gerado', help_text='Status atual do documento', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='documentocliente',
            name='template_usado',
            field=models.CharField(blank=True, help_text='Nome do template usado para gerar o documento', max_length=100, null=True, verbose_name='Template Usado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='assinatura_digital',
            field=models.ImageField(blank=True, help_text='Assinatura digital do responsável legal', null=True, upload_to='clientes/assinaturas/', verbose_name='Assinatura Digital'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, help_text='Usuário que fez a última atualização', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(blank=True, help_text='Bairro da empresa', max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(blank=True, help_text='Cidade da empresa', max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(default='00.000.000/0000-00', help_text='CNPJ da empresa', max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='CNPJ deve estar no formato: 12.345.678/0001-90', regex='^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$')], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='complemento',
            field=models.CharField(blank=True, help_text='Complemento do endereço (sala, andar, etc.)', max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='criado_por',
            field=models.ForeignKey(blank=True, help_text='Usuário que criou o registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email_principal',
            field=models.EmailField(blank=True, help_text='E-mail principal da empresa', max_length=254, null=True, verbose_name='E-mail Principal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.TextField(blank=True, help_text='Endereço completo da empresa', null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(blank=True, help_text='Estado (UF) da empresa', max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='grupo_empresa',
            field=models.ForeignKey(blank=True, help_text='Grupo ao qual a empresa pertence (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas', to='clientes.grupoempresa', verbose_name='Grupo de Empresas'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='inscricao_estadual',
            field=models.CharField(blank=True, help_text='Inscrição estadual da empresa', max_length=20, null=True, verbose_name='Inscrição Estadual'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='inscricao_municipal',
            field=models.CharField(blank=True, help_text='Inscrição municipal da empresa', max_length=20, null=True, verbose_name='Inscrição Municipal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo da empresa', null=True, upload_to='clientes/logos/', verbose_name='Logo da Empresa'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome_fantasia',
            field=models.CharField(blank=True, help_text='Nome fantasia da empresa', max_length=255, null=True, verbose_name='Nome Fantasia'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero',
            field=models.CharField(blank=True, help_text='Número do endereço', max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Observações adicionais sobre a empresa', null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ramo_atividade',
            field=models.CharField(blank=True, help_text='Ramo de atividade da empresa', max_length=255, null=True, verbose_name='Ramo de Atividade'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='razao_social',
            field=models.CharField(default='Empresa Temporária', help_text='Razão social da empresa', max_length=255, verbose_name='Razão Social'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='regime_tributario',
            field=models.CharField(choices=[('simples_nacional', 'Simples Nacional'), ('lucro_presumido', 'Lucro Presumido'), ('lucro_real', 'Lucro Real'), ('mei', 'MEI - Microempreendedor Individual'), ('outro', 'Outro')], default='simples_nacional', help_text='Regime tributário da empresa', max_length=20, verbose_name='Regime Tributário'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='responsavel_legal_cargo',
            field=models.CharField(blank=True, help_text='Cargo do responsável legal na empresa', max_length=100, null=True, verbose_name='Cargo do Responsável Legal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='responsavel_legal_cpf',
            field=models.CharField(default='000.000.000-00', help_text='CPF do responsável legal', max_length=14, validators=[django.core.validators.RegexValidator(message='CPF deve estar no formato: 123.456.789-00', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')], verbose_name='CPF do Responsável Legal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='responsavel_legal_nome',
            field=models.CharField(default='Responsável Temporário', help_text='Nome completo do responsável legal da empresa', max_length=255, verbose_name='Nome do Responsável Legal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('suspenso', 'Suspenso'), ('bloqueado', 'Bloqueado')], default='ativo', help_text='Status atual da empresa', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone_principal',
            field=models.CharField(blank=True, help_text='Telefone principal da empresa', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Formato de telefone inválido. Use: +5511999999999', regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefone Principal'),
        ),
        migrations.AlterField(
            model_name='contatocliente',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Se a pessoa está ativa', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='contatocliente',
            name='cargo',
            field=models.CharField(blank=True, help_text='Cargo da pessoa na empresa', max_length=100, null=True, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='contatocliente',
            name='cliente',
            field=models.ForeignKey(help_text='Empresa onde a pessoa trabalha', on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='clientes.cliente', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='contatocliente',
            name='email',
            field=models.EmailField(blank=True, help_text='E-mail da pessoa (opcional)', max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='contatocliente',
            name='nome',
            field=models.CharField(help_text='Nome completo da pessoa', max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='documentocliente',
            name='arquivo',
            field=models.FileField(help_text='Arquivo do documento', upload_to='clientes/documentos/', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='documentocliente',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Se o documento está ativo', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='documentocliente',
            name='cliente',
            field=models.ForeignKey(help_text='Cliente proprietário do documento', on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='documentocliente',
            name='data_upload',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora do upload', verbose_name='Data do Upload'),
        ),
        migrations.AlterField(
            model_name='documentocliente',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição do documento', null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='documentocliente',
            name='nome',
            field=models.CharField(help_text='Nome descritivo do documento', max_length=255, verbose_name='Nome do Documento'),
        ),
        migrations.AlterField(
            model_name='documentocliente',
            name='tipo_documento',
            field=models.CharField(choices=[('contrato', 'Contrato'), ('boleto', 'Boleto'), ('proposta', 'Proposta'), ('certificado', 'Certificado'), ('licenca', 'Licença'), ('alvara', 'Alvará'), ('comprovante', 'Comprovante'), ('outro', 'Outro')], default='outro', help_text='Tipo do documento', max_length=20, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='documentocliente',
            name='usuario_upload',
            field=models.ForeignKey(blank=True, help_text='Usuário que fez o upload', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário do Upload'),
        ),
        migrations.AlterField(
            model_name='grupoempresa',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Se o grupo está ativo', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='grupoempresa',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição do grupo', null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='grupoempresa',
            name='nome',
            field=models.CharField(help_text='Nome do grupo de empresas', max_length=255, verbose_name='Nome do Grupo'),
        ),
        migrations.AlterField(
            model_name='historicocliente',
            name='campo_alterado',
            field=models.CharField(help_text='Nome do campo que foi alterado', max_length=100, verbose_name='Campo Alterado'),
        ),
        migrations.AlterField(
            model_name='historicocliente',
            name='cliente',
            field=models.ForeignKey(help_text='Cliente que foi alterado', on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='historicocliente',
            name='data_alteracao',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora da alteração', verbose_name='Data da Alteração'),
        ),
        migrations.AlterField(
            model_name='historicocliente',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Observações sobre a alteração', null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='historicocliente',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuário que fez a alteração', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='historicocliente',
            name='valor_anterior',
            field=models.TextField(blank=True, help_text='Valor anterior do campo', null=True, verbose_name='Valor Anterior'),
        ),
        migrations.AlterField(
            model_name='historicocliente',
            name='valor_novo',
            field=models.TextField(blank=True, help_text='Novo valor do campo', null=True, verbose_name='Valor Novo'),
        ),
        migrations.AddIndex(
            model_name='documentocliente',
            index=models.Index(fields=['status'], name='clientes_do_status_fe238b_idx'),
        ),
        migrations.AddIndex(
            model_name='documentocliente',
            index=models.Index(fields=['origem'], name='clientes_do_origem_625b14_idx'),
        ),
    ]
