# Generated by Django 4.2.13 on 2025-10-11 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0004_remove_cliente_clientes_cl_documen_76f212_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do departamento', max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('cor', models.CharField(default='#3B82F6', help_text='Cor no formato hexadecimal (ex: #3B82F6)', max_length=7, verbose_name='Cor')),
                ('max_atendimentos_simultaneos', models.IntegerField(default=5, help_text='Número máximo de atendimentos que cada atendente pode ter ao mesmo tempo', verbose_name='Máximo de Atendimentos Simultâneos')),
                ('tempo_resposta_esperado_minutos', models.IntegerField(default=15, help_text='SLA de tempo de resposta', verbose_name='Tempo de Resposta Esperado (minutos)')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('atendentes', models.ManyToManyField(blank=True, related_name='departamentos', to=settings.AUTH_USER_MODEL, verbose_name='Atendentes')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FilaAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(db_index=True, help_text='ID do chat no WhatsApp', max_length=100, verbose_name='ID do Chat')),
                ('numero_whatsapp', models.CharField(max_length=20, verbose_name='Número WhatsApp')),
                ('mensagem_inicial', models.TextField(blank=True, help_text='Primeira mensagem que gerou o atendimento', verbose_name='Mensagem Inicial')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], db_index=True, default='normal', max_length=10, verbose_name='Prioridade')),
                ('entrou_na_fila_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Entrou na Fila em')),
                ('atribuido_em', models.DateTimeField(blank=True, null=True, verbose_name='Atribuído em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filas_atendimento', to='clientes.cliente', verbose_name='Cliente')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fila', to='atendimento.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Fila de Atendimento',
                'verbose_name_plural': 'Filas de Atendimento',
                'ordering': ['-prioridade', 'entrou_na_fila_em'],
                'indexes': [models.Index(fields=['departamento', 'atribuido_em'], name='atendimento_departa_ed24bf_idx'), models.Index(fields=['prioridade', 'entrou_na_fila_em'], name='atendimento_priorid_692f9d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(db_index=True, max_length=100, verbose_name='ID do Chat')),
                ('numero_whatsapp', models.CharField(max_length=20, verbose_name='Número WhatsApp')),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando Atendente'), ('em_atendimento', 'Em Atendimento'), ('pausado', 'Pausado'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], db_index=True, default='aguardando', max_length=20, verbose_name='Status')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=10, verbose_name='Prioridade')),
                ('tempo_primeira_resposta_segundos', models.IntegerField(blank=True, null=True, verbose_name='Tempo de Primeira Resposta (segundos)')),
                ('tempo_total_atendimento_segundos', models.IntegerField(blank=True, null=True, verbose_name='Tempo Total de Atendimento (segundos)')),
                ('total_mensagens_cliente', models.IntegerField(default=0, verbose_name='Total de Mensagens do Cliente')),
                ('total_mensagens_atendente', models.IntegerField(default=0, verbose_name='Total de Mensagens do Atendente')),
                ('avaliacao', models.IntegerField(blank=True, help_text='Nota de 1 a 5', null=True, verbose_name='Avaliação')),
                ('comentario_avaliacao', models.TextField(blank=True, verbose_name='Comentário da Avaliação')),
                ('observacoes', models.TextField(blank=True, help_text='Notas do atendente sobre o atendimento', verbose_name='Observações Internas')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('iniciado_em', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado em')),
                ('primeira_resposta_em', models.DateTimeField(blank=True, null=True, verbose_name='Primeira Resposta em')),
                ('finalizado_em', models.DateTimeField(blank=True, null=True, verbose_name='Finalizado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('atendente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_atendente', to=settings.AUTH_USER_MODEL, verbose_name='Atendente')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to='clientes.cliente', verbose_name='Cliente')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to='atendimento.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Atendimentos',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['status', 'criado_em'], name='atendimento_status_a86d62_idx'), models.Index(fields=['atendente', 'status'], name='atendimento_atenden_3e5596_idx'), models.Index(fields=['departamento', 'status'], name='atendimento_departa_95f4f6_idx'), models.Index(fields=['chat_id'], name='atendimento_chat_id_2fba71_idx')],
            },
        ),
    ]
