# Generated by Django 4.2.13 on 2025-10-11 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atendimento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferenciaAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(help_text='Motivo informado pelo atendente', verbose_name='Motivo da Transferência')),
                ('aceito', models.BooleanField(default=True, help_text='Se a transferência foi aceita pelo atendente destino', verbose_name='Aceito')),
                ('aceito_em', models.DateTimeField(blank=True, null=True, verbose_name='Aceito em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Transferido em')),
                ('atendente_destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_recebidas', to=settings.AUTH_USER_MODEL, verbose_name='Atendente Destino')),
                ('atendente_origem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Atendente Origem')),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias', to='atendimento.atendimento', verbose_name='Atendimento')),
                ('departamento_destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_entrada', to='atendimento.departamento', verbose_name='Departamento Destino')),
                ('departamento_origem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_saida', to='atendimento.departamento', verbose_name='Departamento Origem')),
            ],
            options={
                'verbose_name': 'Transferência de Atendimento',
                'verbose_name_plural': 'Transferências de Atendimento',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['atendimento', 'criado_em'], name='atendimento_atendim_0c2c12_idx'), models.Index(fields=['atendente_origem', 'criado_em'], name='atendimento_atenden_7c59f7_idx'), models.Index(fields=['atendente_destino', 'criado_em'], name='atendimento_atenden_048472_idx')],
            },
        ),
    ]
